a = input('Digite Algo')
print('o tipo primitivo desse valor é', type(a))
print('Só Tem Espaços ?',a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico ?', a.isalpha())
print('é alfanumerico ?', a.isalnum())
print('esta em maiusculas ?', a.isupper())
print('esta em minusculas ?', a.islower())
print('esta capitalizada ?', a.istitle())
